In [38]:
!pip install opencv-python
!pip install pandas

Requirement already satisfied: opencv-python in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (4.8.1.78)
Requirement already satisfied: numpy>=1.21.2 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from opencv-python) (1.26.1)
Requirement already satisfied: pandas in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (2.1.1)
Requirement already satisfied: numpy>=1.26.0 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting albumentations
  Using cached albumentations-1.3.1-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: numpy>=1.11.1 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from albumentations) (1.26.1)
Requirement already satisfied: scipy>=1.1.0 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from albumentations) (1.11.3)
Collecting scikit-image>=0.16.1 (from albumentations)
  Using cached scikit_image-0.22.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: PyYAML in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from albumentations) (6.0.1)
Collecting qudida>=0.0.4 (from albumentations)
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Collecting opencv-python-headless>=4.1.1 (from albumentations)
  Using cached opencv_python_headless-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting scikit-learn>=0.19.1 (from qudida>=0.0.4->albumentations)
  Using cached scikit_learn-1.3.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: typing-extensions in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from qudida>=0.0.4->albumentations) (4.8.0)
Collecting networkx>=2.8 (from scikit-image>=0.16.1->albumentations)
  Using cached networkx-3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pillow>=9.0.1 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from scikit-image>=0.16.1->albumentations) (10.1.0)
Collecting imageio>=2.27 (from scikit-image>=0.16.1->albumentations)
  Using cached imageio-2.31.5-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: tifffile>=2022.8.12 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from scikit-image>=0.16.1->albumentations) (2023.9.26)
Requirement already satisfied: packaging>=21 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from scikit-image>=0.16.1->albumentations) (23.2)
Collecting lazy_loader>=0.3 (from scikit-image>=0.16.1->albumentations)
  Using cached lazy_loader-0.3-py3-none-any.whl.metadata (4.3 kB)
Collecting joblib>=1.1.1 (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\trabalhos ufpb\pdi\projeto final\.venv\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (3.2.0)
Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
Using cached opencv_python_headless-4.8.1.78-cp37-abi3-win_amd64.whl (38.0 MB)
Using cached scikit_image-0.22.0-cp312-cp312-win_amd64.whl (25.0 MB)
Using cached imageio-2.31.5-py3-none-any.whl (313 kB)
Using cached lazy_loader-0.3-py3-none-any.whl (9.1 kB)
Using cached networkx-3.2-py3-none-any.whl (1.6 MB)
Using cached scikit_learn-1.3.1-cp312-cp312-win_amd64.whl (9.1 MB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Installing collected packages: opencv-python-headless, networkx, lazy_loader, joblib, imageio, scikit-learn, scikit-image, qudida, albumentations

ERROR: Could not install packages due to an OSError: [WinError 5] Acesso negado: 'd:\\Trabalhos UFPB\\PDI\\projeto final\\.venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

In [10]:
import cv2
import os
import numpy as np
import pandas as pd

In [9]:
directory = "imgs\imgs"
h = []
w = []

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    img = cv2.imread(f)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h.append(img.shape[0])
    w.append(img.shape[1])

h = np.array(h)
w = np.array(w)
print(f"Altura da imagem --> Média: {np.mean(h)}, Mediana: {np.median(h)} e Moda:")
print(f"Largura da imagem --> Média: {np.mean(w)}, Mediana: {np.median(w)} e Moda:")

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
C:\Users\Andre\AppData\Local\Temp\ipykernel_29032\3848929428.py:1: SyntaxWarning: invalid escape sequence '\i'
  directory = "imgs\imgs"

Altura da imagem --> Média: 1360.6422160321881, Mediana: 1600.0 e Moda:
Largura da imagem --> Média: 1395.3649025069637, Mediana: 1704.0 e Moda:

In [ ]:
directory = "imgs\imgs"

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    img = cv2.imread(f)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    resized = cv2.resize(img, (1000, 1000))

In [11]:
gab = pd.read_csv("ground_truth.csv")
display(gab)

,img_name,left_eye_left_x,left_eye_left_y,left_eye_right_x,left_eye_right_y,right_eye_left_x,right_eye_left_y,right_eye_right_x,right_eye_right_y,blurred,...,sh_head,sh_face,dark_glasses,flash_lenses,frames_heavy,frame_eyes,hat,veil,mouth,close
0,AR_FDB_m-003-13.png,282,286,328,287,388,281,430,280,1,...,1,1,1,0,1,1,1,0,-1,1
1,AR_FDB_m-051-13.png,277,274,324,271,394,263,441,257,1,...,1,1,1,1,1,1,1,0,-1,1
2,AR_FDB_m-052-22.png,-1,-1,-1,-1,-1,-1,-1,-1,1,...,1,1,0,0,-1,-1,1,1,1,1
3,AR_FDB_m-053-3.png,350,290,397,298,466,300,516,298,1,...,1,1,1,1,1,1,1,1,1,1
4,AR_FDB_m-069-26.png,318,267,357,267,424,269,464,268,1,...,1,1,1,1,1,1,1,0,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3580,Fall2003_04792d24.jpg,1317,622,1401,615,1473,617,1545,625,0,...,-1,0,1,1,1,1,1,1,1,1
3581,Fall2003_04831d08.jpg,820,573,934,568,1076,556,1200,552,1,...,1,1,1,1,1,1,1,1,1,1
3582,Fall2003_04846d36.jpg,1019,777,1078,784,1170,780,1225,766,1,...,-1,0,1,1,1,0,1,1,1,1
3583,PUT_00432012.JPG,855,679,965,679,1141,681,1255,678,1,...,1,1,1,1,1,1,1,1,1,1
3584,PUT_00631021_PX6.png,820,784,921,790,1085,785,1186,771,1,...,1,1,1,1,1,1,1,1,1,1

In [34]:
directory = "imgs\imgs"
data = {"filename": [], "hat": [], "veil": [], "glasses": [], "accessory": []}

for i in range(len(gab)):
    f = os.path.join(directory, gab["img_name"].iloc[i])
    if os.path.isfile(f):
        #Montando o gabarito:
        data["filename"].append(gab["img_name"].iloc[i])
        data["hat"].append(gab["hat"].iloc[i])
        data["veil"].append(gab["veil"].iloc[i])
        data["glasses"].append(gab["dark_glasses"].iloc[i])
        if gab["hat"].iloc[i] == 0 or gab["veil"].iloc[i] == 0 or gab["dark_glasses"].iloc[i] == 0:
            data["accessory"].append(1)
        else:
            data["accessory"].append(0)
        #resize da imagem:
        img = cv2.imread(f)
        resized = cv2.resize(img, (1360, 1360))
        #Salvando a imagem no dataset:
        fd = os.path.join("Dataset", gab["img_name"].iloc[i])
        cv2.imwrite(fd, resized)
    else:
        pass

df = pd.DataFrame(data)
display(df)

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
C:\Users\Andre\AppData\Local\Temp\ipykernel_29032\704876791.py:1: SyntaxWarning: invalid escape sequence '\i'
  directory = "imgs\imgs"

                   filename  hat  veil  glasses  accessory
0       AR_FDB_m-003-13.png    1     0        1          1
1       AR_FDB_m-051-13.png    1     0        1          1
2       AR_FDB_m-052-22.png    1     1        0          1
3        AR_FDB_m-053-3.png    1     1        1          0
4       AR_FDB_m-069-26.png    1     0        1          1
...                     ...  ...   ...      ...        ...
3226  Fall2003_04792d24.jpg    1     1        1          0
3227  Fall2003_04831d08.jpg    1     1        1          0
3228  Fall2003_04846d36.jpg    1     1        1          0
3229       PUT_00432012.JPG    1     1        1          0
3230   PUT_00631021_PX6.png    1     1        1          0

[3231 rows x 5 columns]

In [35]:
print(len(df[df["accessory"] == 1]))

882

In [33]:
print(len(gab[gab["dark_glasses"] == -1]))

2

In [36]:
df.to_csv("gabarito.csv")

In [44]:
gab = pd.read_csv("gabarito.csv")
display(gab)

      Unnamed: 0               filename  hat  veil  glasses  accessory
0              0    AR_FDB_m-003-13.png    1     0        1          1
1              1    AR_FDB_m-051-13.png    1     0        1          1
2              2    AR_FDB_m-052-22.png    1     1        0          1
3              3     AR_FDB_m-053-3.png    1     1        1          0
4              4    AR_FDB_m-069-26.png    1     0        1          1
...          ...                    ...  ...   ...      ...        ...
3226        3226  Fall2003_04792d24.jpg    1     1        1          0
3227        3227  Fall2003_04831d08.jpg    1     1        1          0
3228        3228  Fall2003_04846d36.jpg    1     1        1          0
3229        3229       PUT_00432012.JPG    1     1        1          0
3230        3230   PUT_00631021_PX6.png    1     1        1          0

[3231 rows x 6 columns]

In [49]:
directory = "Dataset"
data = {"filename": [], "hat": [], "veil": [], "glasses": [], "accessory": []}

for i in range(len(gab)):
    f = os.path.join(directory, gab["filename"].iloc[i])
    if os.path.isfile(f):
        if gab["accessory"].iloc[i] == 1:
            #Montando o gabarito:
            data["filename"].append("flipped_"+str(gab["filename"].iloc[i]))
            data["hat"].append(gab["hat"].iloc[i])
            data["veil"].append(gab["veil"].iloc[i])
            data["glasses"].append(gab["glasses"].iloc[i])
            data["accessory"].append(1)

            #flip da imagem:
            img = cv2.imread(f)
            flipped = np.flip(img[:, :, :], axis=1)
            #Salvando a imagem no dataset:
            fd = os.path.join("aumentation", "flipped_"+str(gab["filename"].iloc[i]))
            cv2.imwrite(fd, flipped)
    else:
        pass

df = pd.DataFrame(data)
display(df)

                           filename  hat  veil  glasses  accessory
0       flipped_AR_FDB_m-003-13.png    1     0        1          1
1       flipped_AR_FDB_m-051-13.png    1     0        1          1
2       flipped_AR_FDB_m-052-22.png    1     1        0          1
3       flipped_AR_FDB_m-069-26.png    1     0        1          1
4         flipped_FRGC_04382d54.jpg    0     1        1          1
..                              ...  ...   ...      ...        ...
877         flipped_AR_m-060-25.png    1     0        1          1
878         flipped_AR_w-010-26.png    1     0        1          1
879         flipped_AR_w-045-12.png    1     0        1          1
880   flipped_Fall2002_04516d08.JPG    0     1        1          1
881  flipped_Fall2003_04419d185.jpg    0     1        1          1

[882 rows x 5 columns]

In [50]:
df.to_csv("gabarito_au.csv")